// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHxX-EVyhTldBSDa9Pg1OQH771oFDJWjs',
    appId: '1:421770252027:android:818c7ad49af10943f26a5e',
    messagingSenderId: '421770252027',
    projectId: 'nanny-now-app',
    storageBucket: 'nanny-now-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmhjo1WNctZ2IpWg4pA2WAhT1FbqoEZKI',
    appId: '1:421770252027:ios:38cc63d10d38bf2cf26a5e',
    messagingSenderId: '421770252027',
    projectId: 'nanny-now-app',
    storageBucket: 'nanny-now-app.firebasestorage.app',
    androidClientId: '421770252027-ogoe1rajd5r64drrbonu8ou8budpkc0f.apps.googleusercontent.com',
    iosClientId: '421770252027-fmbna35tb2iqkt36m92u32l8nhdnkhso.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.flutter.app',
  );

}